---
repos:
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.14.13"
    hooks:
      - id: "ruff-check"
        args: ["--fix"]
      - id: "ruff-format"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v1.19.1'
    hooks:
      - id: "mypy"
        args: ["--strict", "."]
        pass_filenames: false
        additional_dependencies:
          - "pocketsearch"
          - "django-stubs[compatible-mypy]"
...
